repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff-format
        files: ^sdks/python/

      - id: ruff
        args: ["--fix"]
        files: ^sdks/python/

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'cd sdks/python && uv run pyright'
        language: system
        files: ^sdks/python/.*\.py$
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: bash -c 'cd sdks/python && uv run pytest -v'
        language: system
        files: ^sdks/python/.*\.py$
        pass_filenames: false
